### ISSUE TITLE
unescaped backslash removes all occurrences of the letter 'r' in output

### ISSUE THREAD

**Issue by ozmrt** [wireghoul/graudit#32] opened 2020-07-15 04:04 UTC
here:

https://github.com/wireghoul/graudit/blob/db44ad2b3910b48d3a7759412d3b089ec18bfb58/graudit#L202

at least when using ggrep on OSX

**Comment by wireghoul** [comment] 2020-07-28 12:44
I am unable to reproduce this, can you provide a concrete example? It's not intended to be escaped as it should match carriage return \x0a not the character r (\x72). Also the code you have highlighted is using sed so your grep version shouldn't matter.

**Comment by ozmrt** [comment] 2020-07-28 14:30
I noticed that the letter 'r' was missing in the output, when sending it to a file e.g. > filename. So with a single backslash, it was removing the r instead of a carriage return. When I added the slash, it correctly read it as \r and removed carriage returns. With sed, I would expect it to be something like s/\\r//g because sed sees the single \ as an escape and removes r instead of \r.

**Comment by paolodm** [comment] 2020-08-09 22:37
Happening for me too. Here's an example:

![image](https://user-images.githubusercontent.com/247525/89743253-50cc1b00-da6f-11ea-87bb-1207cd0dd49d.png)

**Comment by wireghoul** [comment] 2020-08-18 02:36
Can you provide me the output of these two commands:
`sed --version`

`cd graudit/t;bash -x ../graudit -d php exec.php`

As I'm unable to reproduce this issue? \\r is matching two characters, not a regexp special character. I suspect the sed flavour or version is the root cause here.

**Comment by ozmrt** [comment] 2020-08-18 06:09
https://stackoverflow.com/questions/37639496/how-can-i-check-the-version-of-sed-in-os-x
`strings /usr/bin/sed@(#)PROGRAM:sed  PROJECT:text_cmds-101.40.1`

On 18/08/2020 at 12:36 PM, "Eldar Marcussen"  wrote:
	Can you provide me the output of these two commands:
 sed --version 

	cd graudit/t;bash -x ../graudit -d php exec.php 

	As I'm unable to reproduce this issue? r is matching two characters,
not a regexp special character. I suspect the sed flavour or version
is the root cause here.

**Comment by wireghoul** [comment] 2020-08-19 07:18
Updated script to hopefully resolve this, can you pull latest from repo and try again?

**Comment by ozmrt** [comment] 2020-08-19 07:37
Worksforme

On 19/08/2020 at 5:19 PM, "Eldar Marcussen"  wrote:
	Updated script to hopefully resolve this, can you pull latest from
repo and try again?

**Comment by TMFRook** [comment] 2020-08-19 13:22
me as well. thanks!

**Comment by wireghoul** [comment] 2020-08-19 22:50
Cheers, closing this issue 👍

**Closed by wireghoul** 2020-08-19 22:50 UTC
